### ISSUE TITLE
Have to leave filter blank to download whole collection

### ISSUE THREAD

**Issue by snckrz** [macearl/Wallhaven-Downloader#34]
Hey!
I have a collection of 263 wallpapers. I wanted to download them with the script, and entered for the filter `FILTER=111` as that should've included everything, or so I thought. However only 66 images were downloaded. 
After leaving the. `FILTER=` tag empty, it seems that now every image has been downloaded.

**Comment by macearl** [comment]
Is the collection by any chance public? If so i could try to reproduce this on my side

**Comment by snckrz** [comment]
Afaik it has to, otherwise your script wouldn’t work, no?

**Comment by macearl** [comment]
No, if they are your own collections and if you specify an api key from your account they can be private.
Collections only need to be public if you don't specify an api key from your account or if the collections are from other users.

It's been some time since i used or looked at the script and i had completely forgotten that `FILTER` is not used for collections at all, so your settings for it do not matter.

I suspect you have `PARALLEL` set to `1`? It seems that with parallel enabled you can run into cloudflares rate limiting rather quickly.

I just pushed a quick fix which checks if the response code is equal to `429` and if so waits for 30 seconds and then tries again.

**Comment by snckrz** [comment]
I have `Parallel` set to 0. Here are my settings:
```
WPNUMBER=480
STARTPAGE=1
TYPE=collections
CATEGORIES=0
FILTER=
RESOLUTION=
ATLEAST=
ASPECTRATIO=
MODE=favorites
TOPRANGE=
ORDER=desc
COLLECTION="Default"
QUERY=""
COLOR=""
SUBFOLDER=0
USR="snckrz"
PARALLEL=0
THUMBS=24`
```

It's weird that it only works when there is **no** setting in FILTER, so I suppose it has something to do with that. Even when I write 000 in it, it wont work - I have to leave it blank.

**Comment by macearl** [comment]
Did you already try the updated script?

It can't have anything to do with the variable `FILTER` as it is not used while downloading collections.
